services:
  db:
    image: postgis/postgis:16-3.5
    platform: linux/amd64
    container_name: local-music-db-auth-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local_music_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_auth_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_auth_dev:
